apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginxjob
  labels: 
    app: web
spec: 
  schedule: 2 
  jobTemplate:
    metadata:
      name: nginxjob
      labels:
        app: web  
    spec:
      selector: 
        matchLabels:
          key: app
          value: web
      template: 
        metadata: 
          name: nginxjob
          labels: 
            app: web
        spec:
          restartPolicy: OnFailure
          containers:
            - name: nginxjob
              image: nginx:1:23
              args:
                - sleep
                - 1s

                     
  
 

