apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginxjob
  labels: 
    app: web
spec: 
  schedule: 2 * * * *
  jobTemplate:
    metadata:
      name: nginx
      labels:
        app: dev  
    spec:
      template: 
        metadata: 
          name: jenkins-batch
          labels: 
            app: web
        spec:
          restartPolicy: OnFailure
          containers:
            - name: jenkins-job
              image: nginx
              args:
                - sleep
                - 1s

                     
  
 

