## Jobs: Jobs run a single time
---
apiVersion: batch/v1
kind: Job
metadata:
  name: Job1
spec:
  backoffLimit: 2
  template:
    metadata:
      name: alpine
    spec:
      restartPolicy: Never
      containers:
        - name: nginx-job
          image: alpine
          ports:
            - containerPort: 8080
          args:
            - sleep
            - 1s
                     
## Cronjob: while CronJobs run on a scheduled interval
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginxjob
  labels: 
    app: web
spec: 
  schedule: 2 * * * *
  jobTemplate:
    metadata:
      name: nginx
      labels:
        app: dev  
    spec:
      template: 
        metadata: 
          name: jenkins-batch
          labels: 
            app: web
        spec:
          restartPolicy: OnFailure
          containers:
            - name: jenkins-job
              image: nginx
              args:
                - sleep
                - 1s



                     
  
 

