apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginxjob
  labels: 
    app: web
spec: 
   schedule: 2 * * * *
   jobTemplate:
     metadata:
       name: nginx
       labels:
         app: dev  
     spec:
       minReadySeconds: 2
       replicas: 1
       selector: 
         matchExpressions: 
           - key: app
             operator: In
             values: 
               - web
       template: 
         metadata: 
           name: jenkins-batch
           labels: 
             app: web
         spec:
            restartPolicy: OnFailure
            containers:
              - name: jenkins-job
                image: jenkins/jenkins
                args:
                  - sleep
                  - 1s

                     
  
 

