apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: 
  labels:
    app: 
spec:
  minReadySeconds: 2
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      name: 
      labels:
        app: 
    spec:
      containers:
        - name: 
          image: 
          ports:
            - containerPort: 
          nodeSelector: