apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: http-rs-faulty
  labels:
    app: httpd
spec:
  minReadySeconds: 2
  replicas: 1
  selector: 
    matchLabels:
      app: httpd
  template:
    metadata:
      name: httpd
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:2.4.57
          ports:
            - containerPort: 80
          readinessProbe:
            failureThreshold: 1
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 2
            timeoutSeconds: 1
            exec:
              command: 
                - sleep
                - 10MM
          livenessProbe:
            failureThreshold: 1
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec: 
              command:
                - sleep
                - 10MM

