---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-alpine
spec:
  minReadySeconds: 3
  replicas: 5
  template:
    metadata:
      name: jenkins 
    spec:
      containers:
        name: jenkins
        image: 
        ports:
          - containerPort: 8080 
  