---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume-pod
  labels:
    app: mysql-vol
    layer: db
spec:
  containers:
    - name: mysql-pod
      image: mysql:8.0.33
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: volume-test
          mountPath: /var/lib/mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_USER
          value: qtdevops
        - name: MYSQL_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
  volumes:
    - name: volume-test
      persistentVolumeClaim:
        claimName: persisted-volume