---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persisted-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 5Gi
  storageClassName: medium
   
