apiVersion: batch/v1
kind: CronJob
metadata: 
  name: nginx
spec:
  schedule: 2 * * * *
  jobTemplate:
    metadata:
      name: nginxjob
    spec: 
      template: 
        metadata: 
          name: nginx-pod
          labels: 
            app: web
        spec: 
          restartPolicy: OnFailure
          containers:
            - name: nginx-kube
              image: nginx
              ports:
                - containerPort: 80

    
           
    

        

            

 

