---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-job
  labels: 
    app: web
spec:
  minReadySeconds: 3
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: nginx
      labels:
        app: web 
    spec:
      containers:
        - name: nginx
          image: nginx
          command:
            - sleep
            - 10s
        



          
  