---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-job
  labels: 
    app: web
spec:
  minReadySeconds: 3
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: jenkins
      labels:
        app: web 
    spec:
      containers:
        name: jenkins
        image: nginx
        command:
          - sleep
          - 10s
        



          
  