---
apiVersion: v1
kind: Pod
metadata: 
  name: spring-petclinic
spec: 
  containers:
    - name: spring-petclinic
      image: paddutester/spring-petclinic:spc-1.0
      ports: 
        - containerPort: 8080
      protocol: "TCP"    