---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mysql
  labels: 
    app: web
spec: 
  minReadySeconds: 2
  replicas: 1
  selector:
    matchExpressions:  
      - key: test
        operator: In
        values: 
          - web
          - dev
    template: 
      metadata:
        name: mysql-job
        labels: 
          test: dev
      spec:
        containers:
          - name: mysql-pod
            image: mysql:8.0-debian
            ports:
              - name: mysqls
                containerPort: 3306
                protocol: TCP      




   
